#include "AttendancePage.h"
#include "ui_AttendancePage.h"
#include "../Managers/CameraManager.h"
#include "../Managers/FaceRecognitionManager.h"
#include <QMessageBox>
AttendancePage::AttendancePage(CameraManager*c,FaceRecognitionManager*r,QWidget*p):QWidget(p),ui(new Ui::AttendancePage),camera_(c),recognition_(r){ui->setupUi(this);for(int i=0;i<3;++i)ui->cameraCombo->addItem(QString("Camera %1").arg(i),i);connect(ui->startButton,&QPushButton::clicked,this,&AttendancePage::start);connect(ui->stopButton,&QPushButton::clicked,this,&AttendancePage::stop);connect(camera_,&CameraManager::frameReady,this,&AttendancePage::showFrame);connect(camera_,&CameraManager::recognitionUpdated,this,&AttendancePage::updateResult);connect(camera_,&CameraManager::attendanceMarked,this,&AttendancePage::marked);connect(camera_,&CameraManager::errorOccurred,this,[this](const QString&m){QMessageBox::critical(this,"Recognition error",m);stop();});}
AttendancePage::~AttendancePage(){if(camera_->isRunning())camera_->stop();delete ui;}void AttendancePage::start(){if(!recognition_->isLoaded()&&!recognition_->loadModel()){QMessageBox::warning(this,"Model required","Train the LBPH model before starting attendance.");return;}if(camera_->start(ui->cameraCombo->currentData().toInt(),CameraManager::Mode::Attendance)){ui->startButton->setEnabled(false);ui->stopButton->setEnabled(true);ui->confirmationLabel->setText("Recognition running…");}}
void AttendancePage::stop(){camera_->stop();ui->startButton->setEnabled(true);ui->stopButton->setEnabled(false);ui->confirmationLabel->setText("Recognition stopped.");}void AttendancePage::showFrame(const QImage&i){if(isVisible())ui->cameraLabel->setPixmap(QPixmap::fromImage(i).scaled(ui->cameraLabel->size(),Qt::KeepAspectRatio,Qt::SmoothTransformation));}
void AttendancePage::updateResult(const QString&n,const QString&r,int a,const QString&l){ui->nameLabel->setText("Name: "+n);ui->regLabel->setText("Registration: "+r);ui->accuracyLabel->setText(QString("Accuracy: %1%").arg(a));ui->livenessLabel->setText("Liveness: "+l);}
void AttendancePage::marked(const QString&n,const QString&r,const QString&t){ui->confirmationLabel->setStyleSheet("color:#22c55e;font-weight:700;");ui->confirmationLabel->setText("Attendance confirmed for "+n);ui->historyList->insertItem(0,t+"  •  "+n+"  ("+r+")");emit attendanceChanged();}
