#include "DatasetCollectionPage.h"
#include "ui_DatasetCollectionPage.h"
#include "../Student.h"
#include "../Managers/CameraManager.h"
#include <QMessageBox>
DatasetCollectionPage::DatasetCollectionPage(StudentManager*s,CameraManager*c,QWidget*p):QWidget(p),ui(new Ui::DatasetCollectionPage),students_(s),camera_(c){ui->setupUi(this);for(int i=0;i<3;++i)ui->cameraCombo->addItem(QString("Camera %1").arg(i),i);connect(ui->startButton,&QPushButton::clicked,this,&DatasetCollectionPage::start);connect(ui->stopButton,&QPushButton::clicked,this,&DatasetCollectionPage::stop);connect(camera_,&CameraManager::frameReady,this,&DatasetCollectionPage::showFrame);connect(camera_,&CameraManager::captureProgress,this,&DatasetCollectionPage::progress);connect(camera_,&CameraManager::captureFinished,this,&DatasetCollectionPage::finished);connect(camera_,&CameraManager::errorOccurred,this,[this](const QString&m){QMessageBox::critical(this,"Camera error",m);stop();});refreshStudents();}
DatasetCollectionPage::~DatasetCollectionPage(){if(camera_->isRunning())camera_->stop();delete ui;}void DatasetCollectionPage::refreshStudents(){ui->studentCombo->clear();for(const auto&s:students_->getAllStudents())ui->studentCombo->addItem(QString::fromStdString(s.regNo+" — "+s.name),QString::fromStdString(s.regNo));}
void DatasetCollectionPage::start(){if(ui->studentCombo->currentIndex()<0){QMessageBox::warning(this,"No student","Register and select a student first.");return;}ui->captureProgress->setValue(0);if(camera_->start(ui->cameraCombo->currentData().toInt(),CameraManager::Mode::Dataset,ui->studentCombo->currentData().toString())){ui->startButton->setEnabled(false);ui->stopButton->setEnabled(true);}}
void DatasetCollectionPage::stop(){camera_->stop();ui->startButton->setEnabled(true);ui->stopButton->setEnabled(false);}void DatasetCollectionPage::showFrame(const QImage&i){if(isVisible())ui->cameraLabel->setPixmap(QPixmap::fromImage(i).scaled(ui->cameraLabel->size(),Qt::KeepAspectRatio,Qt::SmoothTransformation));}void DatasetCollectionPage::progress(int n,int total){ui->captureProgress->setMaximum(total);ui->captureProgress->setValue(n);ui->counterLabel->setText(QString("%1 / %2 images captured").arg(n).arg(total));}void DatasetCollectionPage::finished(bool ok,const QString&m){stop();QMessageBox::information(this,ok?"Dataset complete":"Capture stopped",m);}
