#include "StudentManagementPage.h"
#include "ui_StudentManagementPage.h"
#include "../Student.h"
#include <QStandardItemModel>
#include <QHeaderView>
#include <QMessageBox>
#include <QDir>
#include <QPixmap>
StudentManagementPage::StudentManagementPage(StudentManager*m,QWidget*p):QWidget(p),ui(new Ui::StudentManagementPage),manager_(m),model_(new QStandardItemModel(this)){ui->setupUi(this);model_->setHorizontalHeaderLabels({"Registration No.","Student Name"});ui->studentTable->setModel(model_);ui->studentTable->horizontalHeader()->setStretchLastSection(true);connect(ui->searchEdit,&QLineEdit::textChanged,this,&StudentManagementPage::filter);connect(ui->addButton,&QPushButton::clicked,this,&StudentManagementPage::addStudent);connect(ui->saveButton,&QPushButton::clicked,this,&StudentManagementPage::saveStudent);connect(ui->deleteButton,&QPushButton::clicked,this,&StudentManagementPage::deleteStudent);connect(ui->studentTable->selectionModel(),&QItemSelectionModel::selectionChanged,this,&StudentManagementPage::selectionChanged);refresh();}
StudentManagementPage::~StudentManagementPage(){delete ui;}void StudentManagementPage::refresh(){populate(ui->searchEdit->text());}
void StudentManagementPage::populate(const QString&q){model_->removeRows(0,model_->rowCount());const auto list=q.trimmed().isEmpty()?manager_->getAllStudents():manager_->search(q.toStdString());for(const auto&s:list)model_->appendRow({new QStandardItem(QString::fromStdString(s.regNo)),new QStandardItem(QString::fromStdString(s.name))});}
void StudentManagementPage::filter(const QString&q){populate(q);}void StudentManagementPage::addStudent(){selectedReg_.clear();ui->regEdit->clear();ui->nameEdit->clear();ui->photoLabel->setText("New student");ui->regEdit->setFocus();}
void StudentManagementPage::saveStudent(){const QString reg=ui->regEdit->text().trimmed(),name=ui->nameEdit->text().trimmed();bool ok=selectedReg_.isEmpty()?manager_->registerStudent(reg.toStdString(),name.toStdString()):manager_->updateStudent(selectedReg_.toStdString(),{reg.toStdString(),name.toStdString()});if(!ok){QMessageBox::warning(this,"Cannot save","Check that the registration number is numeric and unique, and that the name is not empty.");return;}selectedReg_=reg;refresh();emit studentsChanged();}
void StudentManagementPage::deleteStudent(){if(selectedReg_.isEmpty())return;if(QMessageBox::question(this,"Delete student","Delete the selected student? Dataset images and past attendance are retained for audit safety.")!=QMessageBox::Yes)return;if(manager_->deleteStudent(selectedReg_.toStdString())){selectedReg_.clear();ui->regEdit->clear();ui->nameEdit->clear();refresh();emit studentsChanged();}}
void StudentManagementPage::selectionChanged(){const auto rows=ui->studentTable->selectionModel()->selectedRows();if(rows.isEmpty())return;const int row=rows.first().row();selectedReg_=model_->item(row,0)->text();ui->regEdit->setText(selectedReg_);ui->nameEdit->setText(model_->item(row,1)->text());showPhoto(selectedReg_);}
void StudentManagementPage::showPhoto(const QString&reg){QDir d("faces");const auto files=d.entryInfoList({reg+".*.jpg"},QDir::Files,QDir::Time);if(files.isEmpty()){ui->photoLabel->setText("No dataset photo");ui->photoLabel->setPixmap({});return;}QPixmap px(files.first().absoluteFilePath());ui->photoLabel->setPixmap(px.scaled(ui->photoLabel->size(),Qt::KeepAspectRatio,Qt::SmoothTransformation));}
